### PR TITLE
vagrant-pxe: increase CPU cores

### PR DESCRIPTION
**Pull request by starbops**
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

Increase to 8 cores each node.

related: #53

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
this is updated in the [main branch](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/settings.yml) previously, do we need to increase it again?

**Comment by bk201** [comment]
@guangbochen yes, we better adjust too. We observe the CPU usage can be up to 6000+ CPU when longhorn spawns new version pods.

**Comment by guangbochen** [comment]
I see, should we change the target branch to the `main` instead?

**Comment by bk201** [comment]
@guangbochen We need both updated. So we can merge this one can port to main.

**Review by guangbochen — APPROVED** [review]

**Comment by bk201** [comment]
@starbops Please help port the change to the `main` branch as well, thanks!

**Pull request merged**
