### PR TITLE
ansiable: add sftp config

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- we support sftp configuration when installation.

    make default that could be easier to transmit file

related to https://github.com/harvester/harvester-installer/pull/562

### CODE REVIEW

**Review by lanfon72 — APPROVED** [review]
LGTM

**Review by irishgordo — APPROVED** [review]
Awesome!
Thanks @Vicente-Cheng 
LGTM!

**Comment by Vicente-Cheng** [comment]
Hi @folks, I changed this configuration scope, which can be changed easily.

Please help to recheck it!

**Review by lanfon72 — APPROVED** [review]
LGTM

**Review by bk201 — APPROVED** [review]

**Pull request merged**
