### PR TITLE
Bump rancher to v2.8.5

### PR DESCRIPTION
**Pull request by albinsun**

### CODE REVIEW

**Review by lanfon72 — APPROVED** [review]
LGTM, but is it necessary to update the default value ?

**Comment by albinsun** [comment]
> LGTM, but is it necessary to update the default value ?

Yep, we can just provide a default value example.
This just for user convenience to know current defualt value in daily e2e env.
(And also for lazy, to reduce change too much configs when testing :P)

**Review by noahgildersleeve — APPROVED** [review]
LGTM

**Review by irishgordo — APPROVED** [review]
:+1: :smile: - lgtm

**Review by khushboo-rancher — APPROVED** [review]

**Pull request merged**
